
disable_units: True

metrics:
  - name: static
    documentation: Mock metric for testing
    labels:
      type: static
    value:
      kind: static
      value: 100
  - name: ramp
    documentation: Mock metric for testing
    labels:
      type: ramp
    value:
      kind: ramp
      period: 2m
      peak: 100
      invert: true
  - name: square
    documentation: Mock metric for testing
    labels:
      type: square
    value:
      kind: square
      period: 4m
      magnitude: 100
      duty_cycle: 50
  - name: sine
    documentation: Mock metric for testing
    labels:
      type: sine
    value:
      kind: sine
      period: 2m
      amplitude: 100
  - name: gaussian
    documentation: Mock metric for testing
    labels:
      type: gaussian
    value:
      kind: gaussian
      mean: 50
      sigma: 10