name: Release
run-name: Release

on:
  push:
    tags: [ "*.*.*" ]

permissions:
  contents: read

jobs:
  tests:
    uses: mbrunhoej/mocktrics-exporter/.github/workflows/tests.yaml@${{ github.sha }}
    secrets: inherit

  pypi:
    name: Build and Publish to PyPI
    needs: [tests]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mocktrics-exporter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Verify tag matches project version
        run: |
          echo test

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify-metadata: true

