name: CI and Release
run-name: Release

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

# on:
#   push:
#     branches: [ "main" ]
#     tags: [ "*.*.*" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  pypi:
    name: Build and Publish to PyPI
    needs: [tests]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mocktricks-exporter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Verify tag matches project version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION=$(grep -Eo 'version\s*=\s*"[0-9.]+"' pyproject.toml | cut -d'"' -f2)
          TAG_STRIPPED="${TAG#v}"
          echo "Tag: $TAG | Version: $VERSION"
          [ "$TAG_STRIPPED" = "$VERSION" ] || {
            echo "Error: tag ($TAG_STRIPPED) does not match project version ($VERSION)" >&2
            exit 1
          }

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify-metadata: true
          # To test publishing first, uncomment the next line and add TEST_PYPI_API_TOKEN
          # repository-url: https://test.pypi.org/legacy/
